[feat] Preliminary changes

diff --git a/git-hf-staging b/git-hf-staging
--- a/git-hf-staging
+++ b/git-hf-staging
@@ -45,15 +45,15 @@ require_git_repo
 require_hubflow_initialized
 hubflow_load_settings
 VERSION_PREFIX=$(eval "echo `git config --get hubflow.prefix.versiontag`")
-PREFIX=$(git config --get hubflow.prefix.release)
+PREFIX=$(git config --get hubflow.prefix.staging)
 
 usage() {
-	echo "usage: git hf release [list] [-v]"
-	echo "       git hf release start <version> [<base>]"
-	echo "       git hf release finish [-sumpk] <version>"
-	echo "       git hf release cancel <version>"
-	echo "       git hf release push [<name>]"
-	echo "       git hf release pull [<name>]"
+	echo "usage: git hf staging [list] [-v]"
+	echo "       git hf staging start <version> [<base>]"
+	echo "       git hf staging finish [-sumpk] <version>"
+	echo "       git hf staging cancel <version>"
+	echo "       git hf staging push [<name>]"
+	echo "       git hf staging pull [<name>]"
 }
 
 cmd_default() {
@@ -64,22 +64,22 @@ cmd_list() {
 	DEFINE_boolean verbose false 'verbose (more) output' v
 	parse_args "$@"
 
-	local release_branches
+	local staging_branches
 	local current_branch
 	local short_names
-	release_branches=$(echo "$(git_local_branches)" | grep "^$PREFIX")
-	if [ -z "$release_branches" ]; then
-		warn "No release branches exist."
+	staging_branches=$(echo "$(git_local_branches)" | grep "^$PREFIX")
+	if [ -z "$staging_branches" ]; then
+		warn "No staging branches exist."
                 warn ""
-                warn "You can start a new release branch:"
+                warn "You can start a new staging branch:"
                 warn ""
-                warn "    git hf release start <name> [<base>]"
+                warn "    git hf staging start <name> [<base>]"
                 warn ""
 		exit 0
 	fi
 
 	current_branch=$(git branch --no-color | grep '^\* ' | grep -v 'no branch' | sed 's/^* //g')
-	short_names=$(echo "$release_branches" | sed "s ^$PREFIX  g")
+	short_names=$(echo "$staging_branches" | sed "s ^$PREFIX  g")
 
 	# determine column width first
 	local width=0
@@ -147,12 +147,12 @@ require_base_is_on_develop() {
 	fi
 }
 
-require_no_existing_release_branches() {
-	local release_branches=$(echo "$(git_local_branches)" | grep "^$PREFIX")
-	local first_branch=$(echo ${release_branches} | head -n1)
+require_no_existing_staging_branches() {
+	local staging_branches=$(echo "$(git_local_branches)" | grep "^$PREFIX")
+	local first_branch=$(echo ${staging_branches} | head -n1)
 	first_branch=${first_branch#$PREFIX}
-	[ -z "$release_branches" ] || \
-		die "There is an existing release branch ($first_branch). Finish that one first."
+	[ -z "$staging_branches" ] || \
+		die "There is an existing staging branch ($first_branch). Finish that one first."
 }
 
 cmd_start() {
@@ -168,7 +168,7 @@ cmd_start() {
 		hubflow_fetch_latest_changes_from_origin
 	fi
 	require_base_is_on_develop
-	require_no_existing_release_branches
+	require_no_existing_staging_branches
 
 	# sanity checks
 	require_clean_working_tree
@@ -198,7 +198,7 @@ cmd_start() {
 	echo "- Start committing last-minute fixes in preparing your release"
 	echo "- When done, run:"
 	echo
-	echo "     git hf release finish '$VERSION'"
+	echo "     git hf staging finish '$VERSION'"
 	echo
 }
 
@@ -248,7 +248,7 @@ cmd_finish() {
 	fi
 
 	# try to merge into master
-	# in case a previous attempt to finish this release branch has failed,
+	# in case a previous attempt to finish this staging branch has failed,
 	# but the merge into master was successful, we skip it now
 	if ! git_is_branch_merged_into "$BRANCH" "$MASTER_BRANCH"; then
 		git checkout "$MASTER_BRANCH" || \
@@ -260,7 +260,7 @@ cmd_finish() {
 
 	if noflag notag; then
 		# try to tag the release
-		# in case a previous attempt to finish this release branch has failed,
+		# in case a previous attempt to finish this staging branch has failed,
 		# but the tag was set successful, we skip it now
 		local tagname=$VERSION_PREFIX$VERSION
 		if ! git_tag_exists "$tagname"; then
@@ -275,7 +275,7 @@ cmd_finish() {
 
 	# try to merge into develop
 	if noflag nobackmerge; then
-		# in case a previous attempt to finish this release branch has failed,
+		# in case a previous attempt to finish this staging branch has failed,
 		# but the merge into develop was successful, we skip it now
 		if ! git_is_branch_merged_into "$MASTER_BRANCH" "$DEVELOP_BRANCH"; then
 			git checkout "$DEVELOP_BRANCH" || \
@@ -292,12 +292,12 @@ cmd_finish() {
 			fi
 		fi
 	else
-	# in case a previous attempt to finish this release branch has failed,
+	# in case a previous attempt to finish this staging branch has failed,
 	# but the merge into develop was successful, we skip it now
 	if ! git_is_branch_merged_into "$BRANCH" "$DEVELOP_BRANCH"; then
 		git checkout "$DEVELOP_BRANCH" || \
 			die "Could not check out $DEVELOP_BRANCH."
-		# just merge the release branch into the development branch
+		# just merge the staging branch into the development branch
 		git merge --no-ff "$BRANCH" || \
 			die "There were merge conflicts."
 		fi
@@ -331,7 +331,7 @@ cmd_finish() {
 	if flag push ; then
 		echo "- Latest objects have been fetched from '$ORIGIN'"
 	fi
-	echo "- Release branch has been merged into '$MASTER_BRANCH'"
+	echo "- Staging branch has been merged into '$MASTER_BRANCH'"
 	if noflag notag; then
 		echo "- The release was tagged '$tagname'"
 		if noflag nobackmerge; then
@@ -339,19 +339,19 @@ cmd_finish() {
 		fi
 	fi
 	if flag nobackmerge; then
-		echo "- Release branch has been merged into '$DEVELOP_BRANCH'"
+		echo "- Staging branch has been merged into '$DEVELOP_BRANCH'"
 	else
 		echo "- Branch '$MASTER_BRANCH' has been back-merged into '$DEVELOP_BRANCH'"
 	fi
 	if flag keep; then
-		echo "- Release branch '$BRANCH' is still available"
+		echo "- Staging branch '$BRANCH' is still available"
 	else
-		echo "- Release branch '$BRANCH' has been deleted"
+		echo "- Staging branch '$BRANCH' has been deleted"
 	fi
 	if flag push; then
 		echo "- '$DEVELOP_BRANCH', '$MASTER_BRANCH' and tags have been pushed to '$ORIGIN'"
 		if noflag keep ; then
-			echo "- Release branch '$BRANCH' in '$ORIGIN' has been deleted."
+			echo "- Staging branch '$BRANCH' in '$ORIGIN' has been deleted."
 		fi
 	fi
 	echo
@@ -379,7 +379,7 @@ cmd_cancel() {
 	require_branch "$BRANCH"
 	require_clean_working_tree
 	if flag push ; then
-		git push "$ORIGIN" "$BRANCH" || die "Could not push release branch up to $ORIGIN"
+		git push "$ORIGIN" "$BRANCH" || die "Could not push staging branch up to $ORIGIN"
 	fi
 
 	# we only merge into develop if the user hasn't selected the -d flag
@@ -394,12 +394,12 @@ cmd_cancel() {
 
 		# try to merge into develop
 		#
-		# in case a previous attempt to finish this release branch has failed,
+		# in case a previous attempt to finish this staging branch has failed,
 		# but the merge into develop was successful, we skip it now
 		if ! git_is_branch_merged_into "$BRANCH" "$DEVELOP_BRANCH"; then
 			git checkout "$DEVELOP_BRANCH" || \
 				die "Could not check out $DEVELOP_BRANCH."
-			# just merge the release branch into the development branch
+			# just merge the staging branch into the development branch
 			git merge --no-ff "$BRANCH" || \
 				die "There were merge conflicts."
 		fi
@@ -434,14 +434,14 @@ cmd_cancel() {
 		echo "- Latest objects have been fetched from '$ORIGIN'"
 	fi
 	if noflag nodiscard ; then
-		echo "- Release branch has been merged into '$DEVELOP_BRANCH'"
+		echo "- Staging branch has been merged into '$DEVELOP_BRANCH'"
 	fi
 	if flag keep ; then
-		echo "- Release branch '$BRANCH' is still available"
+		echo "- Staging branch '$BRANCH' is still available"
 	else
-		echo "- Release branch '$BRANCH' has been deleted"
+		echo "- Staging branch '$BRANCH' has been deleted"
 		if flag push ; then
-			echo "- Release branch '$BRANCH' in '$ORIGIN' has been deleted."
+			echo "- Staging branch '$BRANCH' in '$ORIGIN' has been deleted."
 		fi
 	fi
 
@@ -500,7 +500,7 @@ parse_remote_name() {
 
 name_or_current() {
 	if [ -z "$NAME" ]; then
-		use_current_release_branch_name
+		use_current_staging_branch_name
 	fi
 }
 
@@ -515,13 +515,13 @@ avoid_accidental_cross_branch_action() {
 }
 
 
-use_current_release_branch_name() {
+use_current_staging_branch_name() {
 	local current_branch=$(git_current_branch)
 	if startswith "$current_branch" "$PREFIX"; then
 		BRANCH=$current_branch
 		NAME=${BRANCH#$PREFIX}
 	else
-		warn "The current HEAD is no release branch."
+		warn "The current HEAD is no staging branch."
 		warn "Please specify a <name> argument."
 		exit 1
 	fi
